### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by HadrienG**
Updated documentation to reflect changes in preparation for 0.5.0

### CODE REVIEW

**Comment by horkko** [comment]
Hi Hadrien,

From `readthedoc.io`, the `API documentation` is empty :cry:

**Comment by HadrienG** [comment]
It should be fixed now!

**Comment by horkko** [comment]
Hi Hadrien,

Yes it works now. By the way, it would be nice also if you could change this line in `setup.py` to a proper location:
```
download_url='https://github.com/HadrienG/taxadb/tarball/0.3a'
```
It is a bit outdated 😅 
Regards

**Comment by HadrienG** [comment]
I didn't want to change before tagging the release on github.

Updated now that 0.5.0 is published on PyPi 🎉

**Pull request merged**
