### PR TITLE
Object implementation for taxadb

### PR DESCRIPTION
**Pull request by horkko**
H Hadrien,

Has we already discussed in pr1, here is the new commits.
I've forgot to mention in the logs that this implementation also refers to #4 and should prevent such error.
Let's start chat around it !

Emmanuel

### CODE REVIEW

**Comment by horkko** [comment]
Hi Hadrien,

I'm thinking of using another documentation style for classes: http://www.sphinx-doc.org/en/stable/ext/napoleon.html
So, I've created a new branch 'docs' to rewrite the doc and try to generate a new API doc for rtd.
What do you think?
Regards

Emmanuel

**Comment by horkko** [comment]
Hi Hadrien,

`docs` branch has been updates. Generated doc is now available.
Please have a look and let me know

Regards

Emmanuel

**Comment by HadrienG** [comment]
Hi,

There were inconsistencies in the naming of the `nodes_file(s)` variable causing the creation of the db to fail. b86bdaa addresses that

I also took the liberty of formatting the code according to PEP8. If it would clash with merging the doc branch we can still git reset and format later.

Concerning the Docstrings, I had started to format according to the Google style guide but hadn't been very strict with myself 😛 
If you don't mind I think we should continue with the Google convention, IMO it's best for readability.

I was about to say that we should make psycopg2 and PyMySQL optional, but I see that you've already addressed that. I was working on f2842b1, hence my ugly last commit 😐 

Last point for today, is there any advantages with having `AccessionID` and `TaxID` in the same file? I find it a bit hard to navigate `taxadb.py` which is > 300 lines


Otherwise, I like the changes so far! And sorry for the somewhat slow feedback, it started as a side project for me 😄

**Comment by horkko** [comment]
Hi Hadrien,

Yes you're right, I've made the modifications later on after seeing that. I think our commit should have merge about it (`nodes_file` and `names_file`).

No problem to force pep8 formatting. On my side, I keep the line length to 120 characters which is should be decreased to 80 regarding pep8 recommandations. Don't worry about pep8 formatting.

I've rewrite all the documentation (docstrings and `.rst` files). I've taken the liberty of adding of small image to illustrate `Taxadb` project. If you don't like it or have a better image to illustrate your project, feel free to replace it. Check the doc directory.

I've made `psycopg2` and `pymysql` optional. However, I haven't been able to test the installation using `pip` so far as explained in the documentation.

No special advantage(s) for having both class `AccessionID` and `TaxID` in one file. We can split both classes into 2 single files `taxadb.accessionid.py` and `taxadb.taxid.py`? Or anything that please you.

No worries for the delay ;)

Emmanuel

PS: I've made some new commits into `doc` and `objects` branches. `objects` has been merged into `docs`

**Comment by horkko** [comment]
Hi Hadrien,

I've made a new branch `split_class` where I've split `AccessionID` and `TaxID` into 2 distinct files `accessionid.py` and `taxid.py`. I've then also updated the corresponding docuemntation to reflect changes.

Let me know what do you think.

Emmanuel

**Comment by HadrienG** [comment]
Hi,

The pip install seems to work. I've tested the following:

```shell
pip install git+https://github.com/horkko/taxadb.git@docs
pip install git+https://github.com/horkko/taxadb.git@docs#egg=taxadb[mysql]
pip install git+https://github.com/horkko/taxadb.git@docs#egg=taxadb[postgres]
```

and it went alright.


I think splitting `taxadb.py` makes sense also from an import perspective. It feels easier to query the database using `taxadb. accessionid` and `taxadb.taxid` than having a `taxadb.taxadb.taxid` . Maybe another solution would to have a module `taxadb.query`, but I'm happy with how it is right now.


Concerning your contributions, I'm happy to keep your name associated with the package. I'm considering submitting taxadb to the [JOSS](http://joss.theoj.org) in the near future. Would you be interested in co-authorship?
As for the versioning, I'd like to switch to [semantic versioning](http://semver.org) for the future release(s). We could do 0.5.0, and prepare for 1.0.0 when the API is deemed stable enough.


I'm finishing testing the creation and querying of the databases with all the DB engines. In parallel, I'd like to make some changes to the documentation. Should we take this in another `docs` PR or here? 


Regards,
Hadrien

**Comment by horkko** [comment]
Hi Hadrien,

Regarding `taxadb.query` I agree that this package class would be great to query taxadb. However, it will be a wrapper over `taxadb.accessionid` and `taxadb.taxid` no? And it won't be something else than calling `taxadb.taxid.<method>`, something we can already do easily by importing `taxadb.accessionid` and `taxadb.taxid`. I agree than `taxadb.query` class would be cleaner in terms of querying taxadb but from my point of view, to much redondant with previous packages. What do you think?
Moreover, implementing `taxadb.query` would enforce to define an API and I don't know how could we make the queries using `taxadb query ...`? `taxadb query --acc <method name> <arguments>` ?
For me a bit complex to define. Unless you already have an idea?

Regarding my contribution, thanks for keeping me in 👍 . I'd be glad to co-author your paper :), at least having my name on the paper ;)
Completely OK with the semantic versioning. Let's start with `0.5.0` for the object implementation, then switch to `1.0.0` when all is ready.

Make any change you'd like in the doc, its up to you. I think it is better to split the PR for this new `docs` point of view.
What do you want to do? I create a new PR against your `doc` branch or you do the PR?

Emmanuel

**Comment by HadrienG** [comment]
Yeah you're right it seems redundant. I'll leave it like it is now.

Not sure about `taxadb query` as a CLI either, seems hard to make convenient to use from a user perspective. What'd the input format be per example? I'll leave the `This has not been implemented yet. Sorry :-(` and leave that problem for future me.

I'll go ahead with the doc PR today. One question: Is the image you added (biobook_taxonomy_graphik_6.png) in the public domain?

**Comment by horkko** [comment]
Hi Hadrien,

I've found the image from google images. It looks it comes from here: http://www.st-james12.lancsngfl.ac.uk/index.php?category_id=342
Maybe find another image, or create one should be better?

**Comment by HadrienG** [comment]
I'm not sure we have the right to use it. 
I might email the image owner to check, I've removed it from the doc in the meantime.

**Comment by HadrienG** [comment]
Hi,

I'm happy enough with the PR to merge! The creation and querying seems to work with sqlite, mysql and postgres 😃 

Could you push your last changes (the `split_class` branch I believe) so I can merge the PR?

I'll finish the doc this week and release 0.5.0 soon afterwards 🎉

**Comment by horkko** [comment]
Hi,

Glad to hear that :) !!
I've just pushed to `split_class` branch and updated `README.md` to reflect changes I forgot to make during last push.

By the way, concerning the logo, I've found this site which generates good stylish logo for free. Give it a try, it could be a solution? (https://www.logomaker.com/)

Emmanuel

**Comment by HadrienG** [comment]
I misspoke, I meant merge `split_class` to the `objects` branch so your last commit would appear here and I can merge and close this PR instead of making a new one.

I''l give a try to logomaker. I was planning of playing with GIMP, but your solution is simpler ;)

**Comment by horkko** [comment]
Done :smirk:

**Comment by horkko** [comment]
Good news! :+1:  When the new release is planned? I'd like to install it internally

**Comment by HadrienG** [comment]
Hopefully it should be in PyPi before the end of the week 😉

**Comment by horkko** [comment]
Great!

**Pull request merged**
