### PR TITLE
Support for PostgreSQL and database driver creation wrapped

### PR DESCRIPTION
**Pull request by horkko**
Hi Hadrien,

I've made some new modifications mainly into `app.py` and `schema.py` in order to have a generic call to one object `DatabaseFactory` which is in charge of creating the right database driver to connect to the database.
Please have a look and let me know what do you think about it.
Regards

Emmanuel

### CODE REVIEW

**Comment by HadrienG** [comment]
Hi,

I've resolved the merge conflicts and will start to take a look this week

Regards,
Hadrien.

**Comment by horkko** [comment]
Hi Hadrien,

Thanks. I've prepared another pull request. There're some changes. Maybe you'll want to see it before I ask for a pull request?

**Comment by HadrienG** [comment]
I guess it is your `object` branch? I'm happy to take a look, and pull requests are great since they are giving me push access to your forks!

**Comment by horkko** [comment]
Yes that's it `objects` branch. I'm finalizing some stuff (`README.md`, tests ...)
I should push today.

**Comment by horkko** [comment]
Hi Hadrien,

You can have a look at my last commits into `objects` branch

Regards

Emmanuel

**Comment by HadrienG** [comment]
These are very interesting changes, and globally in the direction I wanted to go. 
Can you make another PR and we discuss the merging over there? There are probably a few changes I'd like to make, and some questions for you as I'm testing and going through the code.

Thanks!

**Comment by HadrienG** [comment]
Closing this since the `objects` branch has been merged instead

**Pull request closed without merging**
